///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RandomValuesExample.Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchNotepad recording.
    /// </summary>
    [TestModule("a642db3a-f20a-42ae-bf29-fd66caad495d", ModuleType.Recording, 1)]
    public partial class LaunchNotepad : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RandomValuesExample.RandomValuesExampleRepository repository.
        /// </summary>
        public static RandomValuesExample.RandomValuesExampleRepository repo = RandomValuesExample.RandomValuesExampleRepository.Instance;

        static LaunchNotepad instance = new LaunchNotepad();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchNotepad()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchNotepad Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'notepad' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("notepad", "", "", false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
