///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RandomValuesExample.Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UseRandomValue recording.
    /// </summary>
    [TestModule("5ca84ea6-94a9-471a-a6a1-7b83fc5cb52d", ModuleType.Recording, 1)]
    public partial class UseRandomValue : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RandomValuesExample.RandomValuesExampleRepository repository.
        /// </summary>
        public static RandomValuesExample.RandomValuesExampleRepository repo = RandomValuesExample.RandomValuesExampleRepository.Instance;

        static UseRandomValue instance = new UseRandomValue();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UseRandomValue()
        {
            Input = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UseRandomValue Instance
        {
            get { return instance; }
        }

#region Variables

        string _Input;

        /// <summary>
        /// Gets or sets the value of variable Input.
        /// </summary>
        [TestVariable("f88116a5-9807-4eb6-be77-2ab7f24c165d")]
        public string Input
        {
            get { return _Input; }
            set { _Input = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Input'.", new RecordItemIndex(0));
            Keyboard.Press(Input);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
